### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mir4a** [zeropv/zeropv.github.io#1]
Замечания:
- [x] Язык html-документа указан как английский, но содержимое документа на русском https://github.com/zeropv/zeropv.github.io/blob/master/index1.html#L2
- [x] на мой взгляд использование тега `p` внутри тега `li` для оборачивания ссылки не оправдано. Здесь можно было задать стиль ссылке (назначить ссылкам класс) или вставить разрыв строки (тег `br`) https://github.com/zeropv/zeropv.github.io/blob/master/index1.html#L41 (также строки 44, 46)
- [x] есть путаница в отступах (неудобно читать код) https://github.com/zeropv/zeropv.github.io/blob/master/index1.html#L13 https://github.com/zeropv/zeropv.github.io/blob/master/index1.html#L58
  Файл стилей тоже плохо отформатирован — должен быть единый стиль. Например, или ставь пробел перед фигурной скобкой или не ставь, но делай это для всего файла.
- [x] класс `.container` используется несколько раз и в иерархии содержит сам себя, то есть `.container .container`. Этому классу задана ширина 80%, следовательно первый контейнер будет иметь ширину равную [80%](https://github.com/zeropv/zeropv.github.io/blob/master/style1.css#L15) от [515px](https://github.com/zeropv/zeropv.github.io/blob/master/style1.css#L18), вложенный в него контейнер будет иметь ширину 80% от (80% от 515px). Ну, не самое удачное решение, на мой взгляд. Более того, на [46й](https://github.com/zeropv/zeropv.github.io/blob/master/style1.css#L46) и [55й](https://github.com/zeropv/zeropv.github.io/blob/master/style1.css#L55) строке контейнеру опять задается ширина в 80%, фактически задавать то же самое значение нет смысла.
- [x] телу документа задано выравнивание текста по центру, но фактически только текст центрирован только в шапке, в остальных местах переписывается значение на выравнивание по левому краю. Можно было этого избежать и центрировать только там где надо, а не [глобально](https://github.com/zeropv/zeropv.github.io/blob/master/style1.css#L3).

**Comment by zeropv** [comment]
Спасибо за замечания. Очень детальный подход!

**Comment by mir4a** [comment]
ЗАЧЕТ
